server:
  port: 8082  # O el puerto que prefieras

spring:
  application:
    name: ms-ventas-service
  config:
    import: optional:configserver:http://root:123456@localhost:7070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost



